### ISSUE TITLE
Error when checking certain mails.

### ISSUE THREAD

**Issue by Zedifus** [SpinnerMaster/eve-jackknife#9]
When clicking on certain mails, I'm presented with the following error.. 

![unknown](https://cloud.githubusercontent.com/assets/1056030/16216280/8c19c6ae-3761-11e6-882a-55e8b8c58781.png)

Could I have setup my Database incorrectly or something? Everything else works as expected bar this.

Thanks,
-Zedi

**Comment by SpinnerMaster** [comment]
Hi, this project is massively depreciated, please use BoodaBooda's fork here: https://github.com/Jtav1/eve-jacknife
